{"_path":"/docs/errorlog","_dir":"docs","_draft":false,"_partial":false,"_locale":"en","_empty":false,"title":"错误日志分析统计","description":"错误日志分析统计","excerpt":{"type":"root","children":[{"type":"element","tag":"h1","props":{"id":"错误日志分析统计"},"children":[{"type":"text","value":"错误日志分析统计"}]},{"type":"element","tag":"h2","props":{"id":"常见错误类型"},"children":[{"type":"text","value":"常见错误类型"}]},{"type":"element","tag":"h4","props":{"id":"syntaxerror-解析时发生语法错误"},"children":[{"type":"text","value":"SyntaxError 解析时发生语法错误"}]},{"type":"element","tag":"h4","props":{"id":"typeerror-值不是所期待的类型"},"children":[{"type":"text","value":"TypeError 值不是所期待的类型"}]},{"type":"element","tag":"h4","props":{"id":"referenceerror-引用未声明的变量"},"children":[{"type":"text","value":"ReferenceError 引用未声明的变量"}]},{"type":"element","tag":"h4","props":{"id":"rangeerror-一个值不在其所允许的范围或者集合中"},"children":[{"type":"text","value":"RangeError 一个值不在其所允许的范围或者集合中"}]},{"type":"element","tag":"h4","props":{"id":"resourceerror-资源加载错误"},"children":[{"type":"text","value":"ResourceError 资源加载错误"}]},{"type":"element","tag":"h4","props":{"id":"httperror-http请求错误"},"children":[{"type":"text","value":"HttpError Http请求错误"}]},{"type":"element","tag":"h2","props":{"id":"错误搜集"},"children":[{"type":"text","value":"错误搜集"}]},{"type":"element","tag":"h4","props":{"id":"可疑区域增加-try-catch"},"children":[{"type":"text","value":"可疑区域增加 Try-Catch"}]},{"type":"element","tag":"h4","props":{"id":"全局监控-js-异常-windowonerror"},"children":[{"type":"text","value":"全局监控 JS 异常 window.onerror"}]},{"type":"element","tag":"h4","props":{"id":"全局监控静态资源异常-windowaddeventlistener"},"children":[{"type":"text","value":"全局监控静态资源异常 window.addEventListener"}]},{"type":"element","tag":"h4","props":{"id":"捕获没有-catch-的-promise-异常unhandledrejection-事件函数"},"children":[{"type":"text","value":"捕获没有 Catch 的 Promise 异常：unhandledrejection 事件函数"}]},{"type":"element","tag":"h4","props":{"id":"vue-errorhandler-和-react-componentdidcatch"},"children":[{"type":"text","value":"VUE errorHandler 和 React componentDidCatch"}]},{"type":"element","tag":"h4","props":{"id":"监控网页崩溃window-对象的-load-和-beforeunload"},"children":[{"type":"text","value":"监控网页崩溃：window 对象的 load 和 beforeunload"}]}]},"body":{"type":"root","children":[{"type":"element","tag":"h1","props":{"id":"错误日志分析统计"},"children":[{"type":"text","value":"错误日志分析统计"}]},{"type":"element","tag":"h2","props":{"id":"常见错误类型"},"children":[{"type":"text","value":"常见错误类型"}]},{"type":"element","tag":"h4","props":{"id":"syntaxerror-解析时发生语法错误"},"children":[{"type":"text","value":"SyntaxError 解析时发生语法错误"}]},{"type":"element","tag":"h4","props":{"id":"typeerror-值不是所期待的类型"},"children":[{"type":"text","value":"TypeError 值不是所期待的类型"}]},{"type":"element","tag":"h4","props":{"id":"referenceerror-引用未声明的变量"},"children":[{"type":"text","value":"ReferenceError 引用未声明的变量"}]},{"type":"element","tag":"h4","props":{"id":"rangeerror-一个值不在其所允许的范围或者集合中"},"children":[{"type":"text","value":"RangeError 一个值不在其所允许的范围或者集合中"}]},{"type":"element","tag":"h4","props":{"id":"resourceerror-资源加载错误"},"children":[{"type":"text","value":"ResourceError 资源加载错误"}]},{"type":"element","tag":"h4","props":{"id":"httperror-http请求错误"},"children":[{"type":"text","value":"HttpError Http请求错误"}]},{"type":"element","tag":"h2","props":{"id":"错误搜集"},"children":[{"type":"text","value":"错误搜集"}]},{"type":"element","tag":"h4","props":{"id":"可疑区域增加-try-catch"},"children":[{"type":"text","value":"可疑区域增加 Try-Catch"}]},{"type":"element","tag":"h4","props":{"id":"全局监控-js-异常-windowonerror"},"children":[{"type":"text","value":"全局监控 JS 异常 window.onerror"}]},{"type":"element","tag":"h4","props":{"id":"全局监控静态资源异常-windowaddeventlistener"},"children":[{"type":"text","value":"全局监控静态资源异常 window.addEventListener"}]},{"type":"element","tag":"h4","props":{"id":"捕获没有-catch-的-promise-异常unhandledrejection-事件函数"},"children":[{"type":"text","value":"捕获没有 Catch 的 Promise 异常：unhandledrejection 事件函数"}]},{"type":"element","tag":"h4","props":{"id":"vue-errorhandler-和-react-componentdidcatch"},"children":[{"type":"text","value":"VUE errorHandler 和 React componentDidCatch"}]},{"type":"element","tag":"h4","props":{"id":"监控网页崩溃window-对象的-load-和-beforeunload"},"children":[{"type":"text","value":"监控网页崩溃：window 对象的 load 和 beforeunload"}]}],"toc":{"title":"","searchDepth":2,"depth":2,"links":[{"id":"常见错误类型","depth":2,"text":"常见错误类型"},{"id":"错误搜集","depth":2,"text":"错误搜集"}]}},"_type":"markdown","_id":"content:docs:171.errorlog.md","_source":"content","_file":"docs/171.errorlog.md","_extension":"md"}